name: 'Unleash Checker AI'
description: 'Detects and removes unused feature flags using Unleash API and OpenAI.'
inputs:
  repository:
    description: 'The repository to clean.'
    required: true
    default: ${{ github.repository }}
ouputs:
  pull_request:
    description: 'The URL of the pull request that was created.'
    value: ${{ steps.create_pull_request.outputs.pull_request }}
runs:
  using: 'go'
  main: 'cmd/unleash-checker-ai'
permissions:
  contents: 'write'
  pull-requests: 'write'
branding:
  icon: 'activity'
  color: 'green'
