package report

import (
	"fmt"
	"strings"
)

func CreateSummary(staleFlags []string, removedFlags []string) string {
	var output strings.Builder

	output.WriteString("# Unleash Checker Results Report\n\n")
	
	output.WriteString("## Overview\n")
	if len(staleFlags) == 0 {
		output.WriteString("**No stale flags were found**\n\n")
		return output.String()
	}
	output.WriteString(fmt.Sprintf("**Unleash Checker** has detected **%d stale flags**.\n\n", len(staleFlags)))

	if len(removedFlags) > 0 {
		output.WriteString("## Removed Flags\n")
		output.WriteString("The following flags have been removed from the files (due to being stale):\n\n")
		for _, flag := range removedFlags {
			output.WriteString(fmt.Sprintf("- `%s`\n", flag))
		}
		output.WriteString("\n")
	}

	unfoundFlags := difference(staleFlags, removedFlags)
	if len(unfoundFlags) > 0 {
		output.WriteString("## Unfound Flags\n")
		output.WriteString("The following flags were not found in the specified directories:\n\n")
		for _, flag := range unfoundFlags {
			output.WriteString(fmt.Sprintf("- `%s`\n", flag))
		}
		output.WriteString("\n")
	}

	output.WriteString("## Action Items\n")
	output.WriteString("1. Please review the changes\n")
	output.WriteString("2. If everything looks good, commit to the repository\n\n")

	output.WriteString("## Note\n")
	output.WriteString("If you still want to use these flags, consider changing the flag type.\n")
	output.WriteString("For more information, please refer to the following documentation:\n")
	output.WriteString("https://docs.getunleash.io/reference/technical-debt\n\n")

	output.WriteString("---\n\n")
	output.WriteString("This PR was automatically generated by the **Unleash Checker AI GitHub Action**.\n")

	return output.String()
}

func difference(sliceA, sliceB []string) []string {
	var diff []string

	for _, a := range sliceA {
		found := false
		for _, b := range sliceB {
			if a == b {
				found = true
				break
			}
		}
		if !found {
			diff = append(diff, a)
		}
	}

	return diff
}
