name: Unleash Checker AI

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:  

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release
        id: get_release
        run: |
          OS=$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')
          ARCH=$(echo $RUNNER_ARCH | tr '[:upper:]' '[:lower:]')
          if [ "$ARCH" == "x64" ]; then
            ARCH="amd64"
          fi
          RELEASE_INFO=$(curl -s https://api.github.com/repos/kromiii/unleash-checker-ai/releases/latest)
          ASSET_URL=$(echo "$RELEASE_INFO" | jq -r ".assets[] | select(.name | contains(\"$OS\") and contains(\"$ARCH\")) | .browser_download_url")
          if [ -z "$ASSET_URL" ]; then
            echo "Error: No matching asset found for $OS-$ARCH"
            exit 1
          fi
          echo "::set-output name=asset_url::$ASSET_URL"
          echo "::set-output name=version::$(echo "$RELEASE_INFO" | jq -r .tag_name)"

      - name: Download unleash-checker-ai
        run: |
          cd $GITHUB_WORKSPACE
          wget ${{ steps.get_release.outputs.asset_url }} -O unleash-checker-ai.tar.gz
          tar -xzf unleash-checker-ai.tar.gz
          rm unleash-checker-ai.tar.gz
          chmod +x unleash-checker-ai

      - name: Run unleash-checker-ai
        id: unleash-checker
        env:
          UNLEASH_API_ENDPOINT: ${{ secrets.UNLEASH_API_ENDPOINT }}
          UNLEASH_API_TOKEN: ${{ secrets.UNLEASH_API_TOKEN }}
          UNLEASH_PROJECT_ID: ${{ secrets.UNLEASH_PROJECT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          output=$(./unleash-checker-ai example)
          echo "checker_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update stale Unleash flags
          title: 'Update stale Unleash flags'
          body: |
            This PR was automatically generated by the Unleash Checker AI GitHub Action.
            It removes unused or stale Unleash flags.

            Using unleash-checker-ai version: ${{ steps.get_release.outputs.version }}

            Output from unleash-checker-ai:
            ```
            ${{ steps.unleash-checker.outputs.checker_output }}
            ```
          branch: unleash-checker-updates
          delete-branch: true
